
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import home from './index';
import feedback from './'
import Slideshow from './Slideshow';
import router from "next/router"
import { Fragment } from 'react'
import { Menu, Transition } from '@headlessui/react';
import { ChevronDownIcon } from '@heroicons/react/20/solid';
import classNames from 'classnames';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faStar } from '@fortawesome/free-solid-svg-icons';
import * as React from 'react';
import * as ReactDOM from 'react-dom/client';
import { StyledEngineProvider } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Slider from '@mui/material/Slider';
import Timeline from '@mui/lab/Timeline';
import TimelineItem from '@mui/lab/TimelineItem';
import TimelineSeparator from '@mui/lab/TimelineSeparator';
import TimelineConnector from '@mui/lab/TimelineConnector';
import TimelineContent from '@mui/lab/TimelineContent';
import TimelineOppositeContent from '@mui/lab/TimelineOppositeContent';
import TimelineDot from '@mui/lab/TimelineDot';
import FastfoodIcon from '@mui/icons-material/Fastfood';
import LaptopMacIcon from '@mui/icons-material/LaptopMac';
import HotelIcon from '@mui/icons-material/Hotel';
import RepeatIcon from '@mui/icons-material/Repeat';
import VolunteerActivismIcon from '@mui/icons-material/VolunteerActivism';
import Typography from '@mui/material/Typography';
import { handleNavClick } from './utils'; 
import FoodBankIcon from '@mui/icons-material/FoodBank';
import { red } from '@mui/material/colors';
import NewspaperIcon from '@mui/icons-material/Newspaper';
import TempleBuddhistIcon from '@mui/icons-material/TempleBuddhist';
import SportsBasketballIcon from '@mui/icons-material/SportsBasketball';
import GroupsIcon from '@mui/icons-material/Groups';
import MedicationIcon from '@mui/icons-material/Medication';
import { Swiper, SwiperSlide } from 'swiper/react';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import 'tailwindcss/tailwind.css'; // Import Tailwind CSS

// Import required modules
import { EffectCoverflow, Pagination } from 'swiper/modules';


import 'swiper/css/effect-cards';
import 'swiper/css';









const YourComponent: React.FC = () => {

  
  return (
          <div className={styles.container}>
          <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
          </Head>


    <div className="flex items-center justify-center">
  <table className="table-auto">
    <tbody>
      <tr>
        {/* Left Column */}
        <td className={`${styles.text} p-4 lg:w-96 lg:h-96`}>
        <div className="flex justify-center">
          <div className="inline-block bg-[#F6F3E4] p-4 rounded-full w-70"> {/* Increase the width to 56 */}
            <Link href="./feedback" target="_blank" rel="noopener noreferrer">
              <div className=" bg-beb3e5 rounded-full p-4 font-[georgia] text-40 font-bold w-70">Feedback
              <div className="flex items-center justify-center">
  <FontAwesomeIcon icon={faArrowRight} className="fi fi-rr-arrow-right rounded-full p-0.5 text-sm w-10" />
</div>
              </div>
            </Link>
          </div>
        </div>
        </td>

        {/* Right Column */}
        <td className={`${styles.text} p-4 lg:w-96 lg:h-96`}>
        <div className="flex justify-center">
          <div className="inline-block bg-[#F6F3E4] p-4 rounded-full w-70"> {/* Increase the width to 56 */}
            <Link href="./Demo" target="_blank" rel="noopener noreferrer">
              <div className=" bg-beb3e5 rounded-full p-4 font-[georgia] text-40 font-bold w-70">Go Back
              <div className="flex items-center justify-center">
              <FontAwesomeIcon icon={faArrowRight} className="fi fi-rr-arrow-right rounded-full p-0.5 text-sm w-10" />
            </div>
              </div>
            </Link>
          </div>
        </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

    <div className="flex justify-center">
          <div className="inline-block bg-[#F6F3E4] p-4 rounded-full w-100"> {/* Increase the width to 56 */}
          <a href="https://drive.google.com/file/d/1GFbDEpIVxzbKQ3M6xlCxya20VVmTU_74/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
              <div className=" bg-beb3e5 rounded-full p-10 font-[georgia] text-60 font-bold w-90">Resume.pdf
              <div className="flex items-center justify-center">
                  <Image src="/pdf.png" alt="email" width="80" height="8" className="fi fi-rr-arrow-right rounded-full p-0.5 text-sm w-10" />
                </div>
              </div>
            </a>
          </div>
        </div>

     
       

              <div id="contact" className={styles.boxa}>
            <div className={styles.text}>
              <h1 className={styles.h1}>Find Me On</h1>
              <div className={styles.iconContainer}>
              <a href="https://www.facebook.com/thiew.lengfong.5?mibextid=LQQJ4d" target="_blank" rel="noopener noreferrer">
               <Image src="/email.b.gif" alt="email" width="40" height="40" className={styles.icon} />
              </a>
              </div>
              <div className={styles.iconContainer}>
              <a href="https://www.facebook.com/thiew.lengfong.5?mibextid=LQQJ4d" target="_blank" rel="noopener noreferrer">
               <Image src="/facebook.a.png" alt="email" width="40" height="40" className={styles.icon} />
              </a>
          </div>
          <div className={styles.iconContainer}>
          <a href="https://www.instagram.com/leng_fong?igsh=Zmt4cWExYmJ2a3J2&utm_source=qr" target="_blank" rel="noopener noreferrer">
                <Image src="/insta.a.png" alt="email" width="40" height="40" className={styles.icon} />
          </a>
          </div>
          <div className={styles.iconContainer}>
          <a href="tel:+1234567890">
                <Image src="/phone.a.gif" alt="phone" width="40" height="40" className={styles.icon} />
          </a>
          </div>
        </div>
      </div>

   


        

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
        </div>
    

    
    
  )
}

