import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';

const FeedbackPage = () => {
  const top100Films = [
    { label: 'Male' },
    { label: 'Female' },
    { label: 'Prefer Not To Say' },
  ];

  const [selectedGender, setSelectedGender] = useState(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className="min-h-screen flex flex-col justify-center items-center bg-cover bg-center bg-no-repeat mt-0">
        <div className={styles.boxa}>
          <div className={styles.text}>
            <h1 className={styles.h1}>FeedBack Form</h1>
             {/* Autocomplete Component */}
        <div className={`${styles.text} p-4 lg:w-96 lg:h-96`}>
          <div className={styles.contenta}>
          <h1 className={styles.h1}>Select Gender</h1>
            <Autocomplete
              disablePortal
              id="combo-box-demo"
              options={top100Films}
              value={selectedGender}
              onChange={(event, newValue) => setSelectedGender(newValue)}
              sx={{ width: 300 }}
              renderInput={(params) => <TextField {...params} label="Gender" />}
            />
          </div>
        </div>
          </div>
        </div>

        <div className={`${styles.text} p-4 lg:w-96 lg:h-96`}>
          <h1 className={styles.h1}>Go Back</h1>
          <div className={styles.contenta}>
            <div className="p-2 rounded-md ">
              <Link href="/">
                <Image src="/arrow.png" alt="email" width="40" height="40" />
              </Link>
            </div>
          </div>
        </div>

       

        {/* Other components */}
      </main>

      <div id="contact" className={styles.boxa}>
        <div className={styles.text}>
          <h1 className={styles.h1}>Find Me On</h1>
          <div className={styles.iconContainer}>
            {/* Social icons */}
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default FeedbackPage;
